[build]
  functions = "netlify/functions"
  command = "pip install --upgrade pip setuptools wheel && pip install -r requirements.txt"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/main"
  status = 200
